trigger:
- master

jobs:
- job: docs
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: |
        echo "foo"
        ls asdf
        echo "bar"
      displayName: "Test"
    - bash: echo "abc"
      displayName: "Test2"
