name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: |
        ls -al ~/.cargo/registry/
        rustup install stable-i686-unknown-linux-gnu
        cd foo
        cargo +stable-i686-unknown-linux-gnu fetch
