name: CI
on: [push, pull_request]

jobs:
  test1:
    name: Test1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test1
      shell: bash
      run: |
        echo $CARGO_HOME
        find ~/.cargo
        rustup self uninstall -y || true
        find ~/.cargo
