name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: |
        ls -al ~/.cargo
        rustup install beta-i686-unknown-linux-gnu
        cd foo
        export CARGO_HTTP_DEBUG=true
        export CARGO_LOG=cargo::ops::registry=trace
        cargo +beta-i686-unknown-linux-gnu fetch
