name: CI
on: [push, pull_request]

jobs:
  test1:
    name: Test1
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
    - name: Test1
      shell: bash
      run: |
        ls /c/Program\ Files\ \(x86\)
        ls /c/Program\ Files\ \(x86\)/Windows\ Kits
        ls /c/Program\ Files\ \(x86\)/Windows\ Kits/10
        ls /c/Program\ Files\ \(x86\)/Windows\ Kits/10/Debuggers
        ls /c/Program\ Files\ \(x86\)/Windows\ Kits/10/Debuggers/x64
