name: CI
on: [push, pull_request]

jobs:
  test1:
    name: Test1
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Test1
      shell: bash
      run: |
        set -x
        env
        which lldb
        du -sh /c/Program\ Files/LLVM/*
        time rm -rf /c/Program\ Files/LLVM
        lldb --version || true
        lldb -P || true
