name: CI
on: [push, pull_request]

jobs:
  test1:
    name: Test1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: |
        rustc --version
        which cargo
        which rustc
        ls -al ~/.cargo
        ls -al ~/.cargo/bin
