name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test1:
    name: Test1
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - run: ./test.sh
  test2:
    name: Test2
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - run: ./test.sh
