name: CI
on: [push, pull_request]

jobs:
  test1:
    name: Test1
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: |
        rustup --version
        rustc --version
        which cargo
        which rustc
        rustup self update
