name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # build: [windows]
        include:
          - os: ubuntu-latest
          - os: ubuntu-20.04
          #   rust: stable
          # - build: beta
          #   os: ubuntu-latest
          #   rust: beta
          # - build: nightly
          #   os: ubuntu-latest
          #   rust: nightly
          - os: macos-latest
          #   rust: stable
          - os: windows-latest
          #   rust: stable
    steps:
    - uses: actions/checkout@master
    - run: |
        ./install-awscli.sh
      shell: bash


  # test1:
  #   name: Test1
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Test1
  #     shell: bash
  #     run: |
  #       cd foo
  #       cargo -V
  #       cargo run
