name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: See if we can touch a directory in /System
      run: sudo touch /System/somefile
