name: CI
on: [push, pull_request]

jobs:
  test1:
    name: Test1
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: ./lldb-test.sh

  test2:
    name: Test2
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: ./lldb-test.sh

  test3:
    name: Test3
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: ./lldb-test.sh

  test4:
    name: Test4
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: ./lldb-test.sh
