name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: |
        rustup install beta-i686-unknown-linux-gnu
        cd gfetch
        cargo fetch
        CARGO_LOG=debug cargo +beta-i686-unknown-linux-gnu run
