name: CI
on: [push, pull_request]

jobs:
  test1:
    name: Test1
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
    - name: Test1
      shell: bash
      run: |
        pwd
