name: CI
on: [push, pull_request]

jobs:
  test1:
    name: Test1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: ./legion-test.sh

  test2:
    name: Test2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: ./legion-test.sh

  test3:
    name: Test3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: ./legtion-test.sh

  test4:
    name: Test4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: ./legtion-test.sh
