name: CI
on: [push, pull_request]

jobs:
  test1:
    name: Test1
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test2:
    name: Test2
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test3:
    name: Test3
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test4:
    name: Test4
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test5:
    name: Test5
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test6:
    name: Test6
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test7:
    name: Test7
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test8:
    name: Test8
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test9:
    name: Test9
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test10:
    name: Test10
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test11:
    name: Test11
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test12:
    name: Test12
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test13:
    name: Test13
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test14:
    name: Test14
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test15:
    name: Test15
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test16:
    name: Test16
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test17:
    name: Test17
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test18:
    name: Test18
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test19:
    name: Test19
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
  test20:
    name: Test20
    runs-on: ubuntu-latest
    steps:
    - run: |
        cargo new foo
        cd foo
        echo 'deno = "*"' >> Cargo.toml
        cargo generate-lockfile
