name: CI
on: [push, pull_request]

jobs:
  test1:
    name: Test1
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Test1
      run: |
        sudo xcode-select -s /Applications/Xcode_10.3.app
        make -p
