name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - run: |
        ( IFS=:
          for p in $PATH
          do
            echo $p
            ls -al $p || true
          done
        )
      shell: bash
