name: Test
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: windows-2022
    steps:
      # - run: |
      #     ls -al /c/msys64
      #     ls -al /c/msys64/home
      #     ls -al /c/msys64/home/runneradmin
      - run: |
          pwd
          ls -al
      - name: Test
        run: |
          msys2Path="c:/msys64"
          echo "${msys2Path}/usr/bin" >> "${GITHUB_PATH}"
      - run: ./test.sh
