name: Test
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Test
        run: |
          cat /proc/cpuinfo || true
          cat /proc/meminfo || true
