name: Test
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      # - run: ./test.sh
      - run: Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell
      - run: |
          Stop-Service -Name WinDefend -Force
          Set-Service -Name WinDefend -StartupType Disabled
      - run: sleep 20
      - run: Get-MpComputerStatus
        shell: powershell
      - name: Check Windows Indexing Service Status
        run: Get-Service -Name WSearch
        shell: powershell
