name: Test
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v5
      - name: Test
        run: |
          cd foo; \
          for i in {1..400}
          do
            rm -rf target ; cargo test
          done
