name: Test
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test ubuntu-24-arm
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          for i in {1..20}; do cargo run; done

  test2:
    name: Test ubuntu-24-x86_64
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          for i in {1..20}; do cargo run; done
