name: Test
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      # - run: ./test.sh
      - run: Get-MpComputerStatus
        shell: powershell
